### ISSUE TITLE
Similarity with redux-orm?

### ISSUE THREAD

**Issue by markerikson** [ddsol/redux-schema#1]
Looks interesting.  Any comments on similarities or differences with https://github.com/tommikaikkonen/redux-orm ?

**Comment by ddsol** [comment]
I wasn't aware of `redux-orm`, but it looks to have some similarities with `redux-orm`, but I think `redux-schema` is different in a number of ways.

In particular, you never `dispatch` anything. In essence, what `redux-schema` does is allow you to manipulate the state in a way very similar to mutable objects, but without any of the drawbacks. The state is internally still immutable. This is possible because none of the references an app has to any objects contain any data. Instead, they only contain a path reference to the data. Each time a property is read, the path is followed from the root of the state. Whenever it's written, the state is modified using the usual copy-on-write. The properties will always refer to the current state.

So from what I'm seeing, `redux-orm` seems to be about reading the state as well as managing reducers. However, it still involves calling `dispatch` and creating actions and action creators.

With `redux-schema`, it's even possible to work essentially schemaless / freeform:
```
var Data = schema('Data', { '*': schema.Any });
var root = schema([Data]);
var store = new schema.Store({ schema: root });
store.store = redux.createStore(store.reducer);

var data = new Data(store);

data.set('todo', [{
  done: false,
  text: 'get book'
}]);
data.get('todo').push({
  done:false,
  text:'read book'
});
data.get('todo').get('0').set('done', true);
```

Unfortunately the `Proxy` object is not well supported, or the above would look like regular property assignments. So, because property names are not known in advance, you have to use `get` and `set`.

I'll be looking into the details of `redux-orm` now as well.

**Comment by ddsol** [comment]
My inspiration came from [redux-tcomb](https://github.com/gcanti/redux-tcomb).

**Comment by markerikson** [comment]
Hmm.  For what it's worth, redux-orm does not necessarily involve dispatching and stuff itself.  

Basically, you can use it to handle updates (reducers) in one of two ways.  Either you define some reducer functions directly on your model classes, and take the wrapper reducer it generates and plug it into your reducer structure, or you use it as an abstraction layer in your own reducer logic, do some update operations (which are queued up internally), and then return the immutably updated result (ie, like a much nicer and easier-to-read version of doing updates with spreads or Object.assign()).

You can also use it for reading data, ie, `MyModel.withId(someId).someField`, which you'd usually do in `mapStateToProps`.

Really does seem like the use cases here are  pretty similar.

**Comment by ddsol** [comment]
Thanks for the feedback.

I think there are some similarities, and certainly the use cases are very similar. Still, I think there are some big differences.
In `redux-schema` there's no need to ever call/bind dispatch. The dispatch call is always made by the instance and the instance persists across different versions of the state. Different parts of the app can safely hold on to their references. Even if the underlying state object gets swapped out, the reference is still valid, provided that the path still exists.

Also, there aren't any action creators at all. It's possible, but completely optional, to write reducers, but action creators are completely automatic, whether you use typed or untyped objects.

The state as redux sees it may be different from the state the app sees. For instance, a `union` type in the store will contain data on what type is store, but the app doesn't see that. Instead the app just gets the right type of object back. This enables, for instance, to return an `Author` instance on a `Post` rather than just the `id`. Of course, `redux-orm` was designed to help with this as well, although it does still use id's in places as well.

To mutate the "state", it's enough to simply assign properties. This works outside and inside of methods. In `redux-orm` this involves calling action creators, which have to be created separately.

By having the most common operations be built-in to the system, requiring no developer code, no tests are needed at all in many cases.

For instance, the `Book` example in the `redux-orm` readme would be defined like so:
```
var Book = schema('Book', {
      toString() {
        return `Book ${this.name}`;
      },
      authors: [ store.reference('author') ],
      publisher: store.reference('publisher')
    })
    //For completeness, also adding these:
  , Author = schema('Author', {
      name: String
    })
  , Publisher = schema('Publisher', {
      name: String
    })
  ;
var store = new schema.Store({ schema: schema([Book, Author, Publisher]) });
store.store = redux.createStore(store.reducer);

var b = new Book(); //Handles CREATE_BOOK
b.authors.push(new Author(), new Author()); //Handles CREATE_AUTHOR and ADD_AUTHOR_TO_BOOK
b.authors.splice(0, 1); //Handles REMOVE_AUTHOR_FROM_BOOK
b.publisher = new Publisher(); //Handles CREATE_PUBLISHER and ASSIGN_PUBLISHER
b.author.name = 'A.U. Thor'; //Also handles AUTHOR_SET_NAME, etc
b.publisher.name = 'P.U. Blisher';
```
No reducers. No action creators.

`redux-orm` supports back references, which I haven't added yet, but that's a great idea.

It's seems to me that `redux-orm` has a very strong relation to traditional ORMs, as gleaned from its naming conventions. `redux-schema` is more designed to make using the immutable state easy to use while keeping the state serializable. There are no reducers at all, which makes I think is a very powerful system. It reduces boilerplate, mistakes, and test code.

That said, it's in its infancy and needs some more TLC :smile:.

**Comment by markerikson** [comment]
Thanks for the explanation.  I'll have to come back later and go through it to get a better handle on how redux-schema does things.
